### ISSUE TITLE
make images not working

### ISSUE THREAD

**Issue by debianmaster** [openshift/open-service-broker-sdk#14]
`make image`  is throwing following errors

```sh
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x68 pc=0x463447]

goroutine 1 [running]:
panic(0x77be20, 0xc820010150)
	/usr/lib/golang/src/runtime/panic.go:481 +0x3e6
github.com/openshift/open-service-broker-sdk/vendor/k8s.io/kubernetes/cmd/libs/go2idl/conversion-gen/generators.getManualConversionFunctions(0xc82011daa0, 0x0, 0xc820130090)
	/root/go/src/github.com/openshift/open-service-broker-sdk/vendor/k8s.io/kubernetes/cmd/libs/go2idl/conversion-gen/generators/conversion.go:130 +0x277
github.com/openshift/open-service-broker-sdk/vendor/k8s.io/kubernetes/cmd/libs/go2idl/conversion-gen/generators.Packages(0xc82011daa0, 0xc820096400, 0x0, 0x0, 0x0)
	/root/go/src/github.com/openshift/open-service-broker-sdk/vendor/k8s.io/kubernetes/cmd/libs/go2idl/conversion-gen/generators/conversion.go:251 +0x127d
github.com/openshift/open-service-broker-sdk/vendor/k8s.io/gengo/args.(*GeneratorArgs).Execute(0xc820096400, 0xc820016d80, 0x7f43d0, 0x6, 0x89a6e0, 0x0, 0x0)
	/root/go/src/github.com/openshift/open-service-broker-sdk/vendor/k8s.io/gengo/args/args.go:165 +0x2f8
main.main()
	/root/go/src/github.com/openshift/open-service-broker-sdk/vendor/k8s.io/kubernetes/cmd/libs/go2idl/conversion-gen/main.go:72 +0x338
make: *** [.generate_files] Error 2
```

**Comment by bparees** [comment]
sounds like you don't have your $GOPATH set correctly.

sample:
`$ export GOPATH=/home/yourname/go`

and then you should clone the project to:
`/home/yourname/go/src/github.com/openshift/open-service-broker-sdk`

**Comment by jmrodri** [comment]
Wonder if this is related to my recent change to the makefile

**Comment by debianmaster** [comment]
thanks @bparees 
that worked

**Comment by bparees** [comment]
@jmrodri sort of.  there are really two requirements:

1) the project needs to be cloned into a directory structure like src/github.com/openshift/open-service-broker-sdk (nothing but familiarity with Go makes this obvious)
2) the GOPATH needs to be set (was previously handled by the Makefile before your changes)

So yeah, i think there's room for improvement here still.
